url: "https://qaznotquaz.github.io"
baseurl: "/qazs-zeitgeist-library"
title: Qaz's Zeitgeist Library
description: Welcome to the Zeitgeist.

collections:
  snippets:
    output: true
  profiles:
    output: false
  navigation:
    output: true
    permalink: /:name/

collections_dir: pages

permalink: /:collection/:categories/:slug/