url: "https://qaznotquaz.github.io"
baseurl: "/qazs-library"
title: Qaz's Library
description: enjoy your stay!

collections:
  snippets:
    output: true
  profiles:
    output: true
  navigation:
    output: true
    permalink: /:name/

collections_dir: pages

permalink: /:collection/:categories/:slug/
