url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Qaz's Zeitgeist Library
description: Welcome to the Zeitgeist.

collections:
  snippets:
    output: true

collections_dir: snippets

permalink: /:collection/:categories/:slug/